site_name: Status Wiki
site_url: https://wiki.status.im
repo_url: https://github.com/status-im/wiki.status.im/
site_description: 'Everything you need to know about Status, a messenger and browser for Ethereum'
google_analytics: ['UA-79146816-1', 'wiki.status.im']
edit_uri: edit/master/docs/
pages:
  - Welcome: index.md
  - Getting Started:
    - Mission & Core Values : 'getting-started/mission-and-core-values.md'
    - User Guide: 'getting-started/user-guide.md'
    - FAQ: 'getting-started/faq.md'
    - Code of Conduct: 'getting-started/code-of-conduct.md'
    - Developer Introduction: 'contributing/development/introduction.md'
  - Contributing:
    - Developers:
      - Introduction: 'contributing/development/introduction.md'
      - Building Status: 'contributing/development/building-status.md'
      - Adding DApps: 'contributing/development/adding-dapps.md'
    - UX & Design: 'contributing/ux-and-design.md'
    - Testing & Feedback: 'contributing/testing-and-feedback.md'
    - Documenting: 'contributing/documenting.md'
    - Marketing: 'contributing/marketing.md'
    - Translations: 'contributing/translations.md'
  - Community:
    - Slack: 'community/slack.md'
    - Newsletter: 'community/newsletter.md'
    - Blog: 'community/blog.md'
    - Tell a Friend: 'community/tell-a-friend.md'
    - Development: 'community/development.md'
    # - Transcripts: # Slack

  - Proposals:
    - Contact Sharing (WIP): 'proposals/contact-sharing.md'
    - Chat API (WIP): 'proposals/chat-api.md'
    - Discover (WIP): 'proposals/discover.md'
    - Status Messaging (WIP): 'proposals/messaging.md'
    - Exchange (WIP): 'proposals/erc20-exchange.md'
    - Sticker Market (WIP): 'proposals/sticker-market.md'
    - Visual Programming (WIP): 'proposals/visual-programming.md'
    - Moments (WIP): 'proposals/moments.md'
  - License:
    - MPL2: 'licenses/mpl2.md'
    - LGPLv3-static: 'licenses/lgpl-v3.0-static.md'